# Generated by Django 5.2.1 on 2025-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_organization_user_securityoffice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
